#!/bin/bash
set -euo pipefail
BASEDIR=$(dirname "${0}")

# Create site from docs.
cd "${BASEDIR}/../"
mkdocs build
cp CNAME docs/CNAME

# Commit and push docs.
git add .
git commit -m "Update site."
git push
